"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import {
  resolveCapacity,
  validateAllocations,
  unallocatedCapacity,
  type PersonLike,
  type AllocationLike,
  type CapacityContributor,
} from "@/lib/capacity/resolve";
import {
  readChannel,
  readMaster,
  setChannelRaw,
  settlePending,
  transferBetweenChannels,
  setPersonSplit,
  splitPeople,
  suggestDonors,
  workforceFte,
  committedFractionByPerson,
  hypotheticalHires,
  reductionRequirement,
} from "@/lib/capacity/workforce";
import { runPortfolioSimulation } from "@/lib/forecast/portfolio";
import { confidenceAtDay, type SimulationResult, type WorkItem, type DecisionGate } from "@/lib/forecast/simulate";
import { computeMomentum } from "@/lib/momentum/compute";
import { computeMomentumTrend, type MomentumTrend } from "@/lib/momentum/trend";
import { applyScenarioInputDelta, type ScenarioInputDelta, type ScenarioInputScope } from "@/lib/scenario/inputDelta";
import { compareToBaseline } from "@/lib/scenario/compare";
import ForecastField, { type FieldScope } from "@/components/portfolio/ForecastField";
import ScenarioInspector, {
  type InspectorFocus,
  type CapacityBasisView,
  type SwitchCostScopeView,
} from "@/components/portfolio/ScenarioInspector";
import ScenarioBar, { type ScenarioCapacityLine } from "@/components/portfolio/ScenarioBar";
import PortfolioMixer, { CHANNEL_ACCENTS } from "@/components/portfolio/PortfolioMixer";
import SplitPatchbay from "@/components/portfolio/SplitPatchbay";
import type { ChannelView } from "@/components/portfolio/MixerChannel";
import InstrumentRail from "@/components/instrument/InstrumentRail";
import CommandMenu from "@/components/instrument/CommandMenu";
import { mutateReality } from "@/lib/instrument/reality";
import type { DependencyDelta, DependentDelta } from "@/lib/portfolio/explain";

// The Instrument. GET /api/portfolio/inputs is the one expensive network
// call (Linear + findings + context, per Scope), fetched once on mount;
// every control interaction after that re-runs resolveCapacity and
// runPortfolioSimulation -- the same pure modules the server uses for the
// saved forecast -- entirely in the browser.
//
// Capacity model: PEOPLE ARE THE CAPACITY. The mixer beneath the field
// moves a finite pool of embodied humans between projects (see
// lib/capacity/workforce.ts); a fader redistributes, and only the Master's
// Workforce control changes how many humans exist. The forecast field above
// is the consequence, drawn from the same simulation the channels read.

interface CapacityBasisPayload {
  kind: "allocations" | "explicit" | "inferred";
  contributors?: CapacityContributor[];
  value?: number;
  assignees?: string[];
  remainingIssueCount?: number;
  unassignedCount?: number;
}

interface ScopeInputRow {
  scopeId: string;
  name: string;
  targetDate: string | null;
  dependsOnScopeIds: string[];
  items: WorkItem[];
  gates: DecisionGate[];
  teamCapacity: number;
  capacitySource: "allocations" | "explicit" | "inferred";
  explicitTeamCapacity: number | null;
  lastReport: { generatedAt: string; likelyDate: string; confidenceAtTarget: number | null } | null;
  reportHistory: {
    generatedAt: string;
    likelyDate: string;
    confidenceAtTarget: number | null;
    shippedCount: number;
    resolvedSinceLastCount: number;
  }[];
  capacityBasis: CapacityBasisPayload;
}

interface PersonRow {
  id: string;
  name: string;
  fte: number;
  active: boolean;
  /** Generated by the embodied-capacity migration to stand in for a legacy
      per-project number. Surfaced on the Master so inherited assumption is
      distinguishable from people Nic actually named. */
  synthetic?: boolean;
}

interface AllocationRow {
  id: string;
  personId: string;
  scopeId: string;
  fraction: number;
}

interface PortfolioInputsResponse {
  startDate: string;
  scopes: ScopeInputRow[];
  people: PersonRow[];
  allocations: AllocationRow[];
  contextSwitchCostPct: number;
}

function pairKey(personId: string, scopeId: string): string {
  return `${personId}::${scopeId}`;
}
function addDays(date: Date, days: number): Date {
  const d = new Date(date);
  d.setUTCDate(d.getUTCDate() + Math.round(days));
  return d;
}
function dayOffset(startDate: Date, date: Date): number {
  return (date.getTime() - startDate.getTime()) / 86400000;
}

// Ticks for the shared axis, aiming for roughly 6-10 labels however wide
// the range is. A portfolio usually spans weeks, so short spans get dated
// week markers; long spans fall back to month/quarter steps.
function niceDayStep(spanDays: number): number | null {
  for (const step of [2, 3, 7, 14, 28]) {
    if (spanDays / step <= 10) return step;
  }
  return null;
}

function monthStep(spanDays: number): number {
  const spanMonths = spanDays / 30.44;
  if (spanMonths <= 10) return 1;
  if (spanMonths <= 24) return 2;
  if (spanMonths <= 48) return 3;
  if (spanMonths <= 96) return 6;
  return 12;
}

function axisTicks(startDate: Date, minDay: number, maxDay: number): { day: number; label: string }[] {
  const span = Math.max(1, maxDay - minDay);
  const ticks: { day: number; label: string }[] = [];
  const dayStep = niceDayStep(span);

  if (dayStep !== null) {
    const first = Math.ceil(minDay / dayStep) * dayStep;
    for (let day = first; day <= maxDay; day += dayStep) {
      ticks.push({
        day,
        label: addDays(startDate, day).toLocaleDateString(undefined, { month: "short", day: "numeric", timeZone: "UTC" }),
      });
    }
    return ticks;
  }

  const step = monthStep(span);
  const first = addDays(startDate, minDay);
  const cursor = new Date(Date.UTC(first.getUTCFullYear(), first.getUTCMonth(), 1));
  let guard = 0;
  while (guard++ < 200) {
    const day = dayOffset(startDate, cursor);
    if (day > maxDay) break;
    if (day >= minDay) {
      ticks.push({
        day,
        label: cursor.toLocaleDateString(undefined, { month: "short", year: "2-digit", timeZone: "UTC" }),
      });
    }
    cursor.setUTCMonth(cursor.getUTCMonth() + step);
  }
  return ticks;
}

export default function PortfolioPageClient() {
  const pathname = usePathname();
  const router = useRouter();

  const [data, setData] = useState<PortfolioInputsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // THE SCENARIO IS AN ALLOCATION PICTURE. null = untouched, so Reality's
  // own allocations are what the mixer is reading.
  const [scenarioAllocations, setScenarioAllocations] = useState<AllocationLike[] | null>(null);
  // People the scenario has hired but Reality has not. Real capacity for
  // the duration of the hypothetical; never persisted without an explicit
  // commit.
  const [hires, setHires] = useState<PersonLike[]>([]);
  // Capacity a fader asked for that nobody in the portfolio can supply.
  const [requiredByScope, setRequiredByScope] = useState<Map<string, number>>(new Map());
  const [switchCostPct, setSwitchCostPct] = useState(0);
  const [patchbayOpen, setPatchbayOpen] = useState(false);
  // Which channel the pointer is on, so its swim lane above can wake. Pure
  // presentation -- it never touches the scenario.
  const [hoveredScopeId, setHoveredScopeId] = useState<string | null>(null);
  // The two channels mid-transfer. Held briefly so both strips and both
  // lanes read as one action rather than two coincidences.
  const [transferPair, setTransferPair] = useState<string[]>([]);
  const [patchbayError, setPatchbayError] = useState<string | null>(null);

  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [saveSummary, setSaveSummary] = useState<{ text: string; hadBlocks: boolean } | null>(null);

  const [selectedScopeId, setSelectedScopeId] = useState<string | null>(null);
  const [removingId, setRemovingId] = useState<string | null>(null);
  const [removeError, setRemoveError] = useState<string | null>(null);

  const [railHidden, setRailHidden] = useState(false);
  const [inspectorOpen, setInspectorOpen] = useState(true);
  const [inspectorFocus, setInspectorFocus] = useState<InspectorFocus>(null);
  const [commandOpen, setCommandOpen] = useState(false);
  const [allocationsOpen, setAllocationsOpen] = useState(false);

  const [pendingTargets, setPendingTargets] = useState<Map<string, string>>(new Map());

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/portfolio/inputs");
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error ?? "Couldn't load portfolio data.");
      }
      const body: PortfolioInputsResponse = await res.json();
      setData(body);
      setScenarioAllocations(null);
      setHires([]);
      setRequiredByScope(new Map());
      setSwitchCostPct(body.contextSwitchCostPct);
      setPendingTargets(new Map());
      setSaveSummary(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      const meta = e.metaKey || e.ctrlKey;
      if (meta && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setCommandOpen((v) => !v);
      }
      if (meta && e.key === "\\") {
        e.preventDefault();
        setRailHidden((v) => !v);
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  const scenarioScopes: ScenarioInputScope[] | null = useMemo(() => {
    if (!data) return null;
    const startDate = new Date(data.startDate);
    return data.scopes.map((s) => ({
      scopeId: s.scopeId,
      items: s.items,
      gates: s.gates,
      dependsOnScopeIds: s.dependsOnScopeIds,
      explicitTeamCapacity: s.explicitTeamCapacity,
      teamCapacity: s.teamCapacity,
      capacitySource: s.capacitySource,
      startDate,
      targetDate: s.targetDate ? new Date(s.targetDate) : null,
    }));
  }, [data]);

  const baseline = useMemo(() => {
    if (!data || !scenarioScopes) return null;
    const baselineDelta: ScenarioInputDelta = {
      allocations: data.allocations.map((a) => ({ personId: a.personId, scopeId: a.scopeId, fraction: a.fraction })),
      hypotheticalPeople: [],
      contextSwitchCostPct: data.contextSwitchCostPct,
    };
    try {
      return runPortfolioSimulation(applyScenarioInputDelta(scenarioScopes, data.people, baselineDelta));
    } catch {
      return null;
    }
  }, [data, scenarioScopes]);

  // THE POOL THE MIXER PLAYS. Reality's people plus anyone the scenario has
  // hired -- a hypothetical hire is a real unit of capacity for as long as
  // the hypothetical lasts, and flows down the identical path.
  const allPeople: PersonLike[] = useMemo(() => [...(data?.people ?? []), ...hires], [data, hires]);

  // The scenario's allocation picture. Starts as Reality's own and is
  // rewritten by conserving transactions (lib/capacity/workforce.ts), never
  // by assignment -- so it can never contain more people than exist.
  const currentAllocations: AllocationLike[] = useMemo(
    () => scenarioAllocations ?? (data?.allocations ?? []).map((a) => ({ personId: a.personId, scopeId: a.scopeId, fraction: a.fraction })),
    [scenarioAllocations, data]
  );

  const workforceState = useMemo(
    () => ({ people: allPeople, allocations: currentAllocations }),
    [allPeople, currentAllocations]
  );

  const overAllocated = useMemo(() => validateAllocations(allPeople, currentAllocations), [allPeople, currentAllocations]);
  const unallocated = useMemo(() => unallocatedCapacity(allPeople, currentAllocations), [allPeople, currentAllocations]);

  // Capacity the scenario asked for that the portfolio does not contain.
  // Simulated as a dedicated person so Nic can see what the extra body
  // would buy -- and refused at commit, because it is not a person.
  const requiredRecord = useMemo(() => Object.fromEntries(requiredByScope), [requiredByScope]);
  const totalRequired = useMemo(() => [...requiredByScope.values()].reduce((t, v) => t + v, 0), [requiredByScope]);

  const previewDelta: ScenarioInputDelta = useMemo(() => {
    const phantoms: PersonLike[] = [];
    const allocations = [...currentAllocations];
    let n = 0;
    for (const [scopeId, fte] of requiredByScope) {
      if (fte <= 1e-6) continue;
      const id = `required-${scopeId}-${n++}`;
      phantoms.push({ id, name: "Required", fte, active: true });
      allocations.push({ personId: id, scopeId, fraction: 1 });
    }
    return {
      allocations,
      hypotheticalPeople: phantoms,
      contextSwitchCostPct: switchCostPct,
    };
  }, [currentAllocations, requiredByScope, switchCostPct]);

  const [preview, setPreview] = useState<Map<string, SimulationResult> | null>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => {
    if (!data || !scenarioScopes || overAllocated.length > 0) return;
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      const specs = applyScenarioInputDelta(scenarioScopes, data.people, previewDelta);
      try {
        setPreview(runPortfolioSimulation(specs));
      } catch {
        // A hypothetical dependsOnScopeIds cycle can't happen from this UI.
      }
    }, 110);
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [data, scenarioScopes, previewDelta, overAllocated.length]);

  const startDateObj = useMemo(() => (data ? new Date(data.startDate) : null), [data]);

  const axis = useMemo(() => {
    if (!data || !startDateObj) return null;
    const days: number[] = [0];
    for (const s of data.scopes) {
      for (const r of [baseline?.get(s.scopeId), preview?.get(s.scopeId)]) {
        if (!r) continue;
        days.push(r.percentiles.p10, r.percentiles.p90);
      }
      const t = pendingTargets.get(s.scopeId) ?? s.targetDate;
      if (t) days.push(dayOffset(startDateObj, new Date(t)));
    }
    const minDay = Math.min(0, ...days);
    const maxDayRaw = Math.max(...days);
    const maxDay = maxDayRaw + Math.max(8, maxDayRaw * 0.16);
    return { minDay, maxDay, ticks: axisTicks(startDateObj, minDay, maxDay) };
  }, [data, startDateObj, baseline, preview, pendingTargets]);

  // What each Scope will actually be simulated at -- read straight off the
  // embodied model, the same call applyScenarioInputDelta makes, so the
  // channel readout and the forecast can never be two calculations.
  const scenarioCapacityByScope = useMemo(() => {
    const out = new Map<string, number>();
    if (!data) return out;
    for (const s of data.scopes) {
      const resolved = resolveCapacity(s.scopeId, allPeople, currentAllocations, switchCostPct);
      out.set(s.scopeId, (resolved.capacity ?? 0) + (requiredByScope.get(s.scopeId) ?? 0));
    }
    return out;
  }, [data, allPeople, currentAllocations, switchCostPct, requiredByScope]);

  const effectiveSelectedScopeId = selectedScopeId ?? data?.scopes[0]?.scopeId ?? null;

  // Reality's own raw allocation per Scope -- what the fader is compared
  // against to decide whether a channel carries a change.
  const realityRawByScope = useMemo(() => {
    const out = new Map<string, number>();
    if (!data) return out;
    const reality = { people: data.people, allocations: data.allocations.map((a) => ({ personId: a.personId, scopeId: a.scopeId, fraction: a.fraction })) };
    for (const s of data.scopes) out.set(s.scopeId, readChannel(reality, s.scopeId, switchCostPct).raw);
    return out;
  }, [data, switchCostPct]);

  const changedScopeIds = useMemo(() => {
    const out = new Set<string>();
    if (!data) return out;
    for (const s of data.scopes) {
      const now = readChannel(workforceState, s.scopeId, switchCostPct).raw + (requiredByScope.get(s.scopeId) ?? 0);
      if (Math.abs(now - (realityRawByScope.get(s.scopeId) ?? 0)) > 1e-6) out.add(s.scopeId);
    }
    return out;
  }, [data, workforceState, switchCostPct, requiredByScope, realityRawByScope]);

  const changedScopeNames = useMemo(
    () => (data?.scopes ?? []).filter((s) => changedScopeIds.has(s.scopeId)).map((s) => s.name),
    [data, changedScopeIds]
  );

  const switchCostChanged = !!data && switchCostPct !== data.contextSwitchCostPct;
  const dirty = changedScopeIds.size > 0 || switchCostChanged || hires.length > 0 || totalRequired > 1e-6;

  const selectedScopeDeps = useMemo(() => {
    const empty: { dependsOn: DependencyDelta[]; dependents: DependentDelta[] } = { dependsOn: [], dependents: [] };
    if (!data || !effectiveSelectedScopeId) return empty;
    const scope = data.scopes.find((s) => s.scopeId === effectiveSelectedScopeId);
    if (!scope) return empty;
    const deltaFor = (scopeId: string): number => {
      const b = baseline?.get(scopeId);
      const p = preview?.get(scopeId) ?? b;
      return compareToBaseline(b, p).deltaDays;
    };
    const dependsOn: DependencyDelta[] = scope.dependsOnScopeIds.map((id) => ({
      scopeId: id,
      name: data.scopes.find((s) => s.scopeId === id)?.name ?? id,
      deltaDays: deltaFor(id),
    }));
    const dependents: DependentDelta[] = data.scopes
      .filter((s) => s.dependsOnScopeIds.includes(effectiveSelectedScopeId))
      .map((s) => ({ scopeId: s.scopeId, name: s.name, deltaDays: deltaFor(s.scopeId) }));
    return { dependsOn, dependents };
  }, [data, baseline, preview, effectiveSelectedScopeId]);

  const momentumByScope = useMemo(() => {
    const out = new Map<string, MomentumTrend>();
    if (!data) return out;
    for (const s of data.scopes) {
      if (!s.lastReport) continue;
      const b = baseline?.get(s.scopeId);
      if (!b) continue;
      const m = computeMomentum(
        { generatedAt: new Date(), likelyDate: b.likelyDate, confidenceAtTarget: b.confidenceAtTarget },
        {
          generatedAt: new Date(s.lastReport.generatedAt),
          likelyDate: new Date(s.lastReport.likelyDate),
          confidenceAtTarget: s.lastReport.confidenceAtTarget,
        }
      );
      const latest = s.reportHistory[s.reportHistory.length - 1];
      out.set(
        s.scopeId,
        computeMomentumTrend(
          m,
          latest
            ? {
                generatedAt: new Date(latest.generatedAt),
                shippedCount: latest.shippedCount,
                resolvedSinceLastCount: latest.resolvedSinceLastCount,
              }
            : null
        )
      );
    }
    return out;
  }, [data, baseline]);

  const fieldScopes: FieldScope[] = useMemo(() => {
    if (!data) return [];
    return data.scopes.map((s) => ({
      scopeId: s.scopeId,
      name: s.name,
      dependsOnScopeIds: s.dependsOnScopeIds,
      targetDate: s.targetDate,
      changed: changedScopeIds.has(s.scopeId),
      // The lane wakes when its channel below is touched -- the coupling
      // that makes "this fader controls THAT project" instant.
      active: hoveredScopeId === s.scopeId || transferPair.includes(s.scopeId),
      recede: (!!hoveredScopeId || transferPair.length > 0) &&
        hoveredScopeId !== s.scopeId && !transferPair.includes(s.scopeId),
    }));
  }, [data, changedScopeIds, hoveredScopeId, transferPair]);

  // Every channel whose allocation the scenario has moved. Under the
  // embodied model there is no such thing as an unpersistable capacity
  // change -- a fader move IS an allocation change -- so the old
  // "can this be committed truthfully" split is gone. The only thing that
  // can block a commit now is asking for people who do not exist.
  const capacityLinesForBar: ScenarioCapacityLine[] = useMemo(() => {
    if (!data) return [];
    return data.scopes
      .filter((s) => changedScopeIds.has(s.scopeId))
      .map((s) => ({
        scopeId: s.scopeId,
        scopeName: s.name,
        realityFte: realityRawByScope.get(s.scopeId) ?? 0,
        scenarioFte: readChannel(workforceState, s.scopeId, switchCostPct).raw + (requiredByScope.get(s.scopeId) ?? 0),
      }));
  }, [data, changedScopeIds, realityRawByScope, workforceState, switchCostPct, requiredByScope]);

  // Context-switch reach, derived entirely from Reality's own sources.
  const switchCostScopes: SwitchCostScopeView[] = useMemo(() => {
    if (!data) return [];
    const scopeCountByPerson = new Map<string, number>();
    for (const a of currentAllocations) {
      if (a.fraction <= 0) continue;
      scopeCountByPerson.set(a.personId, (scopeCountByPerson.get(a.personId) ?? 0) + 1);
    }
    const nameById = new Map(data.people.map((p) => [p.id, p.name]));
    return data.scopes.map((s) => {
      const here = currentAllocations.filter((a) => a.scopeId === s.scopeId && a.fraction > 0);
      return {
        scopeId: s.scopeId,
        name: s.name,
        source: s.capacitySource,
        trackedPeople: here.length,
        splitPeople: here
          .filter((a) => (scopeCountByPerson.get(a.personId) ?? 1) > 1)
          .map((a) => nameById.get(a.personId) ?? a.personId),
      };
    });
  }, [data, currentAllocations]);

  const splitPeopleCount = useMemo(
    () => new Set(switchCostScopes.flatMap((s) => s.splitPeople)).size,
    [switchCostScopes]
  );
  const trackedScopeCount = switchCostScopes.filter((s) => s.source === "allocations").length;

  // ---- interaction handlers -------------------------------------------

  // THE FADER. Raising a channel takes free capacity from the pool and
  // reports any shortfall by name; it never quietly drains a neighbour and
  // never invents a person. Lowering returns capacity to free. Both are
  // transactions on the same finite workforce -- see
  // lib/capacity/workforce.ts.
  //
  // The fader holds the REQUESTED value, not the achieved one. readChannel()
  // already carries an unmet request as a phantom dedicated person, so the
  // request survives in the model; what hid it was the fader's ceiling
  // (faderMax, below), which used to sit at HALF the workforce. Past it the
  // cap stopped moving while the underlying value kept climbing -- the
  // control looked stuck at exactly the moment it was being asked for most.
  // The control obeys; the model explains; Reality commit is what refuses.
  const onFader = useCallback(
    (scopeId: string, requestedRaw: number) => {
      const result = setChannelRaw(workforceState, scopeId, requestedRaw, switchCostPct);
      const pending = new Map(requiredByScope);
      if (result.required > 1e-6) pending.set(scopeId, result.required);
      else pending.delete(scopeId);
      // Lowering this channel may have freed the people another channel was
      // already asking for. Settle those claims before rendering, so the
      // shortfall clears in the same gesture that resolved it.
      const settled = settlePending(
        workforceState.people,
        result.allocations,
        pending,
        switchCostPct,
        scopeId
      );
      setScenarioAllocations(settled.allocations);
      setRequiredByScope(settled.required);
    },
    [workforceState, switchCostPct, requiredByScope]
  );

  // Resolving a deficit by taking from a named donor: both channels move as
  // ONE action, and the workforce total does not change.
  const onTakeFrom = useCallback(
    (donorScopeId: string) => {
      const recipient = [...requiredByScope.entries()].find(([, v]) => v > 1e-6);
      if (!recipient) return;
      const [scopeId, needed] = recipient;
      // PHYSICAL ACTION FIRST. Both strips light before the numbers move, so
      // the eye reads one person crossing the rack rather than two unrelated
      // readouts changing.
      setTransferPair([donorScopeId, scopeId]);
      window.setTimeout(() => setTransferPair([]), 1500);
      const result = transferBetweenChannels(workforceState, donorScopeId, scopeId, needed, switchCostPct);
      setScenarioAllocations(result.allocations);
      setRequiredByScope((prev) => {
        const next = new Map(prev);
        const still = Math.max(0, needed - (result.achievedRaw - readChannel(workforceState, scopeId, switchCostPct).raw));
        if (still > 1e-6) next.set(scopeId, still);
        else next.delete(scopeId);
        return next;
      });
    },
    [workforceState, requiredByScope, switchCostPct]
  );

  // Hiring: the one act that changes how much human capacity exists. The
  // new units go straight onto the channel that needed them.
  const onHire = useCallback(
    (fte: number) => {
      const recipient = [...requiredByScope.entries()].find(([, v]) => v > 1e-6);
      const fresh = hypotheticalHires(Math.max(1, Math.round(fte)), hires.length + 1);
      const grown = { people: [...allPeople, ...fresh], allocations: currentAllocations };
      setHires((prev) => [...prev, ...fresh]);
      if (recipient) {
        const [scopeId, needed] = recipient;
        const target = readChannel(grown, scopeId, switchCostPct).raw + needed;
        const result = setChannelRaw(grown, scopeId, target, switchCostPct);
        setScenarioAllocations(result.allocations);
        setRequiredByScope((prev) => {
          const next = new Map(prev);
          if (result.required > 1e-6) next.set(scopeId, result.required);
          else next.delete(scopeId);
          return next;
        });
      } else {
        setScenarioAllocations(currentAllocations);
      }
    },
    [allPeople, currentAllocations, requiredByScope, hires.length, switchCostPct]
  );

  // Setting the workforce total directly. Growing adds anonymous units;
  // shrinking takes them from free capacity, and reports what must be
  // released first when free capacity is not enough -- an allocated human
  // never just vanishes.
  const onWorkforce = useCallback(
    (targetFte: number) => {
      const current = workforceFte(allPeople);
      const delta = targetFte - current;
      if (delta > 1e-6) {
        setHires((prev) => [...prev, ...hypotheticalHires(Math.round(delta), hires.length + 1)]);
        return;
      }
      if (delta < -1e-6) {
        // Only ever release units nobody is using; the requirement readout
        // on the Master says how much project allocation must come down.
        const committed = committedFractionByPerson(currentAllocations);
        let toDrop = -delta;
        const dropped = new Set<string>();
        for (const p of [...hires].reverse()) {
          if (toDrop <= 1e-6) break;
          if ((committed.get(p.id) ?? 0) > 1e-6) continue;
          dropped.add(p.id);
          toDrop -= p.fte;
        }
        if (dropped.size > 0) setHires((prev) => prev.filter((p) => !dropped.has(p.id)));
      }
    },
    [allPeople, currentAllocations, hires]
  );

  // Dividing one human. Their fractions must still total at most 1.0 --
  // a person split 50/50 is one person, and the model must never be able
  // to say otherwise.
  const onSetSplit = useCallback(
    (personId: string, lines: { scopeId: string; fraction: number }[]) => {
      const result = setPersonSplit(workforceState, personId, lines);
      setPatchbayError(result.error);
      if (!result.error) setScenarioAllocations(result.allocations);
    },
    [workforceState]
  );

  function scrubTarget(scopeId: string, iso: string) {
    setPendingTargets((prev) => {
      const next = new Map(prev);
      next.set(scopeId, iso);
      return next;
    });
  }

  async function saveTargetDate(scopeId: string) {
    const targetDate = pendingTargets.get(scopeId);
    if (targetDate === undefined) return;
    try {
      const res = await mutateReality(`/api/scopes/${scopeId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetDate }),
      });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body.error ?? "Couldn't save the target date.");
      setData((prev) =>
        prev ? { ...prev, scopes: prev.scopes.map((s) => (s.scopeId === scopeId ? { ...s, targetDate } : s)) } : prev
      );
      setPendingTargets((prev) => {
        const next = new Map(prev);
        next.delete(scopeId);
        return next;
      });
    } catch (err) {
      setSaveError(err instanceof Error ? err.message : "Couldn't save the target date.");
    }
  }

  // "Set actual capacity" -- corrects REALITY, not a hypothetical. Writes
  // straight through the existing PATCH /api/scopes/:id and reloads, so the
  // Scope's source becomes explicit exactly as it would from Scope settings.
  async function saveRealityCapacity(scopeId: string, fte: number) {
    const res = await mutateReality(`/api/scopes/${scopeId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ teamCapacity: fte }),
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok) throw new Error(body.error ?? "Couldn't set the capacity.");
    await load();
  }

  async function removePerson(personId: string) {
    setRemoveError(null);
    setRemovingId(personId);
    try {
      const res = await mutateReality(`/api/people/${personId}`, { method: "DELETE" });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error ?? "Couldn't remove that person.");
      }
      await load();
    } catch (err) {
      setRemoveError(err instanceof Error ? err.message : "Couldn't remove that person.");
    } finally {
      setRemovingId(null);
    }
  }

  function discard() {
    if (!data) return;
    setScenarioAllocations(null);
    setHires([]);
    setRequiredByScope(new Map());
    setSwitchCostPct(data.contextSwitchCostPct);
    setPendingTargets(new Map());
    setSaveError(null);
    setSaveSummary(null);
    setPatchbayError(null);
  }

  // REALITY MUST PENCIL. A scenario may audition people the portfolio does
  // not have -- that is useful planning -- but it cannot be written down,
  // because there is nobody to write down. Everything else the mixer can
  // express is a redistribution of humans who exist, and commits cleanly.
  const canCommit = overAllocated.length === 0 && totalRequired <= 1e-6;

  async function save() {
    if (!data || !canCommit) return;
    setSaving(true);
    setSaveError(null);
    setSaveSummary(null);
    try {
      // Anonymous units for anyone the scenario hired. Only now, on an
      // explicit commit, does a hypothetical person become a real one.
      const hireIdMap = new Map<string, string>();
      for (const hire of hires) {
        const res = await mutateReality("/api/people", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ name: hire.name, fte: hire.fte }),
        });
        const body = await res.json().catch(() => ({}));
        if (!res.ok) throw new Error(body.error ?? "Couldn't add to the workforce.");
        hireIdMap.set(hire.id, body.person?.id ?? body.id);
      }

      // Every person the scenario touched, sent as their complete new
      // picture -- the allocations endpoint replaces per person.
      const personIds = new Set<string>();
      for (const a of data.allocations) personIds.add(a.personId);
      for (const a of currentAllocations) personIds.add(a.personId);

      const payload: { personId: string; scopeId: string; fraction: number }[] = [];
      for (const personId of personIds) {
        const realId = hireIdMap.get(personId) ?? personId;
        for (const scope of data.scopes) {
          const line = currentAllocations.find((a) => a.personId === personId && a.scopeId === scope.scopeId);
          payload.push({ personId: realId, scopeId: scope.scopeId, fraction: line?.fraction ?? 0 });
        }
      }

      if (payload.length > 0) {
        const putRes = await mutateReality("/api/allocations", {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ allocations: payload }),
        });
        const putBody = await putRes.json().catch(() => ({}));
        if (!putRes.ok) throw new Error(putBody.error ?? "Couldn't save allocations.");
      }

      if (switchCostPct !== data.contextSwitchCostPct) {
        const settingsRes = await mutateReality("/api/portfolio-settings", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ contextSwitchCostPct: switchCostPct }),
        });
        if (!settingsRes.ok) {
          const b = await settingsRes.json().catch(() => ({}));
          throw new Error(b.error ?? "Couldn't save the context-switch setting.");
        }
      }

      const summaryParts: string[] = [];
      if (hires.length > 0) {
        summaryParts.push(`workforce +${hires.reduce((t, h) => t + h.fte, 0).toFixed(1)} FTE`);
      }
      if (changedScopeNames.length > 0) summaryParts.push(`${changedScopeNames.join(", ")} reallocated`);
      if (summaryParts.length > 0) setSaveSummary({ text: summaryParts.join(" · "), hadBlocks: false });

      await load();
    } catch (err) {
      setSaveError(err instanceof Error ? err.message : "Couldn't save.");
    } finally {
      setSaving(false);
    }
  }

  function openInspector(focus: InspectorFocus) {
    setInspectorOpen(true);
    setInspectorFocus(focus);
  }

  async function relabelPerson(personId: string, name: string) {
    // A label, nothing more. Deliberately writes only `name`, so there is
    // no path by which renaming someone could move a forecast.
    await mutateReality(`/api/people/${personId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name }),
    });
    await load();
  }

  // ---- the mixer's readings -------------------------------------------

  const scopeNameById = useMemo(
    () => new Map((data?.scopes ?? []).map((s) => [s.scopeId, s.name])),
    [data]
  );
  const accentByScope = useMemo(
    () => new Map((data?.scopes ?? []).map((s, i) => [s.scopeId, CHANNEL_ACCENTS[i % CHANNEL_ACCENTS.length]])),
    [data]
  );

  const master = useMemo(
    () => readMaster(workforceState, (data?.scopes ?? []).map((s) => s.scopeId), switchCostPct, requiredRecord),
    [workforceState, data, switchCostPct, requiredRecord]
  );

  const splits = useMemo(() => splitPeople(workforceState, switchCostPct), [workforceState, switchCostPct]);

  const inheritedFte = useMemo(
    () => (data?.people ?? []).filter((p) => p.synthetic && p.active).reduce((t, p) => t + p.fte, 0),
    [data]
  );

  // One shared fader ceiling, so channels are visually comparable and a
  // fader's travel means the same thing everywhere on the surface.
  //
  // Derived from the workforce, never from any channel's current value:
  // if the ceiling responded to what a channel is asking for, the scale
  // would rescale under the hand mid-drag. It carries two people of
  // headroom above the whole workforce so a shortfall can always be
  // auditioned, and it is a floor of six so a small team still gets a
  // readable throw. Six is a minimum, not the model's maximum.
  const faderMax = useMemo(
    () => Math.max(6, Math.ceil(master.workforce) + 2),
    [master.workforce]
  );

  const channelViews: ChannelView[] = useMemo(() => {
    if (!data) return [];
    return data.scopes.map((s, i) => {
      const reading = readChannel(workforceState, s.scopeId, switchCostPct, requiredByScope.get(s.scopeId) ?? 0);
      const b = baseline?.get(s.scopeId);
      const p = preview?.get(s.scopeId) ?? b;
      const deltaDays = b && p ? Math.round((p.likelyDate.getTime() - b.likelyDate.getTime()) / 86400000) : 0;
      return {
        scopeId: s.scopeId,
        name: s.name,
        accent: CHANNEL_ACCENTS[i % CHANNEL_ACCENTS.length],
        // The SAME simulation result the swim lane above is drawing.
        likelyDate: p
          ? p.likelyDate.toLocaleDateString(undefined, { month: "short", day: "numeric", timeZone: "UTC" })
          : "—",
        deltaDays,
        raw: reading.raw,
        effective: reading.effective,
        splitRaw: reading.splitRaw,
        splitPeople: reading.splitPeople,
        required: reading.required,
        changed: changedScopeIds.has(s.scopeId),
        gateCount: s.gates.length,
        completionDays: p?.completionDaysSorted ?? [],
      };
    });
  }, [data, workforceState, switchCostPct, requiredByScope, baseline, preview, changedScopeIds]);

  const deficit = useMemo(() => {
    const entry = [...requiredByScope.entries()].find(([, v]) => v > 1e-6);
    return entry ? { scopeId: entry[0], fte: entry[1] } : null;
  }, [requiredByScope]);

  const donors = useMemo(
    () =>
      deficit
        ? suggestDonors(workforceState, deficit.scopeId, deficit.fte, (data?.scopes ?? []).map((s) => s.scopeId), switchCostPct)
        : [],
    [deficit, workforceState, data, switchCostPct]
  );

  const patchbayPeople = useMemo(
    () =>
      allPeople
        .filter((p) => p.active)
        .map((p) => ({
          personId: p.id,
          label: p.name,
          fte: p.fte,
          lines: currentAllocations
            .filter((a) => a.personId === p.id && a.fraction > 1e-6)
            .map((a) => ({ scopeId: a.scopeId, fraction: a.fraction })),
        }))
        .sort((a, b) => b.lines.length - a.lines.length || a.label.localeCompare(b.label)),
    [allPeople, currentAllocations]
  );

  // ---- render ----------------------------------------------------------

  const shell = (children: React.ReactNode) => (
    <div className="instrument fixed inset-0 flex overflow-hidden">
      <InstrumentRail
        pathname={pathname}
        hidden={railHidden}
        onToggle={() => setRailHidden((v) => !v)}
        onOpenCommand={() => setCommandOpen(true)}
      />
      {children}
    </div>
  );

  if (loading && !data) {
    return shell(
      <div className="flex-1 flex items-center justify-center text-[12px] text-[var(--i-text-faint)]">
        Loading portfolio…
      </div>
    );
  }
  if (error) {
    return shell(<div className="flex-1 flex items-center justify-center text-[12px] text-[var(--i-red)]">{error}</div>);
  }
  if (!data) return null;

  if (data.scopes.length === 0) {
    return shell(
      <div className="flex-1 flex items-center justify-center text-[12px] text-[var(--i-text-faint)]">
        No Scope configured yet. Add one at /scopes to see a portfolio view.
      </div>
    );
  }

  const selectedScope = effectiveSelectedScopeId
    ? data.scopes.find((s) => s.scopeId === effectiveSelectedScopeId) ?? null
    : null;
  const selectedBaseline = effectiveSelectedScopeId ? baseline?.get(effectiveSelectedScopeId) : undefined;
  const selectedPreview = effectiveSelectedScopeId ? preview?.get(effectiveSelectedScopeId) : undefined;
  const selectedActive = selectedPreview ?? selectedBaseline;

  const selectedTargetIso = selectedScope
    ? pendingTargets.get(selectedScope.scopeId) ?? selectedScope.targetDate
    : null;
  const selectedConfidence =
    selectedActive && selectedTargetIso && startDateObj
      ? confidenceAtDay(selectedActive.completionDaysSorted, dayOffset(startDateObj, new Date(selectedTargetIso)))
      : null;
  const spreadDays = selectedActive
    ? Math.round(selectedActive.percentiles.p90 - selectedActive.percentiles.p10)
    : null;
  const fmtDay = (d: Date) => d.toLocaleDateString(undefined, { month: "short", day: "numeric", timeZone: "UTC" });
  const spreadRange =
    selectedActive && startDateObj
      ? {
          earliest: fmtDay(addDays(startDateObj, selectedActive.percentiles.p10)),
          latest: fmtDay(addDays(startDateObj, selectedActive.percentiles.p90)),
        }
      : null;
  const sinceLabel = selectedScope?.lastReport ? fmtDay(new Date(selectedScope.lastReport.generatedAt)) : null;

  const trendSeries: number[] = selectedScope
    ? (() => {
        const pts = selectedScope.reportHistory.map((r) => new Date(r.likelyDate).getTime());
        const b = baseline?.get(selectedScope.scopeId);
        if (b) pts.push(b.likelyDate.getTime());
        return pts;
      })()
    : [];

  // Setting a first target: default it to the current P50, the one date the
  // model can actually justify as a starting point, then let the flag be
  // dragged from there.
  function setInitialTarget() {
    if (!selectedScope || !selectedActive || !startDateObj) return;
    scrubTarget(selectedScope.scopeId, addDays(startDateObj, selectedActive.percentiles.p50).toISOString().slice(0, 10));
  }

  const basisPayload = selectedScope?.capacityBasis;
  const capacityBasis: CapacityBasisView =
    basisPayload?.kind === "allocations"
      ? { kind: "allocations", contributors: basisPayload.contributors ?? [] }
      : basisPayload?.kind === "explicit"
        ? { kind: "explicit", value: basisPayload.value ?? selectedScope!.teamCapacity }
        : {
            kind: "inferred",
            assignees: basisPayload?.assignees ?? [],
            remainingIssueCount: basisPayload?.remainingIssueCount ?? 0,
            unassignedCount: basisPayload?.unassignedCount ?? 0,
          };

  return shell(
    <>
      <div className="flex-1 min-w-0 flex flex-col">
        <ScenarioBar
          dirty={dirty}
          hasPendingTargets={pendingTargets.size > 0}
          saving={saving}
          canCommit={canCommit}
          overAllocated={overAllocated.length > 0}
          capacityLines={capacityLinesForBar}
          namedTransferCount={changedScopeIds.size}
          switchCostChanged={switchCostChanged}
          aggregateConversions={[]}
          blockedCapacityScopes={[]}
          blockedMoves={
            totalRequired > 1e-6
              ? [
                  {
                    personId: "required",
                    personName: `${totalRequired.toFixed(1)} FTE`,
                    blockedReason:
                      "the portfolio does not contain these people. Take capacity from another project, split someone, or increase the workforce.",
                  },
                ]
              : []
          }
          onCommit={save}
          onDiscard={discard}
          onOpenAllocations={() => setAllocationsOpen(true)}
          saveError={saveError}
          saveSummary={saveSummary}
        />

        <div className="flex-1 min-h-0 flex">
          <div className="flex-1 min-w-0 flex flex-col" style={{ background: "var(--i-bg)" }}>
            <ForecastField
              scopes={fieldScopes}
              baseline={baseline}
              preview={preview}
              axis={axis}
              startDate={startDateObj!}
              dirty={dirty}
              selectedScopeId={effectiveSelectedScopeId}
              onSelectScope={setSelectedScopeId}
              onScrubTarget={scrubTarget}
              pendingTargets={pendingTargets}
              onSaveTarget={saveTargetDate}
              portfolioLikely={
                (() => {
                  let max: number | null = null;
                  for (const s of data.scopes) {
                    const r = preview?.get(s.scopeId) ?? baseline?.get(s.scopeId);
                    if (r) max = Math.max(max ?? -Infinity, r.likelyDate.getTime());
                  }
                  return max === null ? null : new Date(max);
                })()
              }
              portfolioDeltaDays={(() => {
                let a: number | null = null;
                let b: number | null = null;
                for (const s of data.scopes) {
                  const pr = preview?.get(s.scopeId) ?? baseline?.get(s.scopeId);
                  const bl = baseline?.get(s.scopeId);
                  if (pr) a = Math.max(a ?? -Infinity, pr.likelyDate.getTime());
                  if (bl) b = Math.max(b ?? -Infinity, bl.likelyDate.getTime());
                }
                return a !== null && b !== null ? Math.round((a - b) / 86400000) : 0;
              })()}
              portfolioGatedBy={(() => {
                let max: number | null = null;
                let name: string | null = null;
                for (const s of data.scopes) {
                  const r = preview?.get(s.scopeId) ?? baseline?.get(s.scopeId);
                  if (r && (max === null || r.likelyDate.getTime() > max)) {
                    max = r.likelyDate.getTime();
                    name = s.name;
                  }
                }
                return name;
              })()}
            />

            <PortfolioMixer
              channels={channelViews}
              master={master}
              faderMax={faderMax}
              selectedScopeId={effectiveSelectedScopeId}
              contextSwitchCostPct={switchCostPct}
              reductionRequired={reductionRequirement(workforceState, master.workforce)}
              inheritedFte={inheritedFte}
              deficitScopeId={deficit?.scopeId ?? null}
              deficitFte={deficit?.fte ?? 0}
              donors={donors}
              scopeNameById={scopeNameById}
              splits={splits}
              onSelect={setSelectedScopeId}
              onFader={onFader}
              onTakeFrom={onTakeFrom}
              onSplitSomeone={() => setPatchbayOpen(true)}
              onHire={onHire}
              onContextSwitch={(pct) => setSwitchCostPct(Math.round(pct))}
              onWorkforce={onWorkforce}
              onOpenSplits={() => setPatchbayOpen(true)}
              onOpenGates={() => router.push("/decisions")}
              onExplainSwitchCost={() => openInspector("switchCost")}
              hoveredScopeId={hoveredScopeId}
              onHover={setHoveredScopeId}
              transferPair={transferPair}
              dormantCount={Math.max(1, 8 - channelViews.length)}
            />
          </div>

          {/* Below ~1280px there isn't room for a 296px narration panel and
              a legible field at once; the field wins. */}
          {selectedScope && inspectorOpen ? (
            <ScenarioInspector
              scope={{
                scopeId: selectedScope.scopeId,
                name: selectedScope.name,
                targetDate: selectedScope.targetDate,
                capacitySource: selectedScope.capacitySource,
              }}
              baseline={selectedBaseline}
              preview={selectedPreview}
              dirty={dirty}
              changedScopeNames={changedScopeNames}
              dependsOn={selectedScopeDeps.dependsOn}
              dependents={selectedScopeDeps.dependents}
              trend={momentumByScope.get(selectedScope.scopeId) ?? null}
              realityCapacity={selectedScope.teamCapacity}
              scenarioCapacity={scenarioCapacityByScope.get(selectedScope.scopeId) ?? selectedScope.teamCapacity}
              capacityBasis={capacityBasis}
              onSaveRealityCapacity={(fte) => saveRealityCapacity(selectedScope.scopeId, fte)}
              onManagePeople={() => setAllocationsOpen(true)}
              switchCostPct={switchCostPct}
              switchCostScopes={switchCostScopes}
              focus={inspectorFocus}
              onCollapse={() => setInspectorOpen(false)}
            />
          ) : (
            <button
              onClick={() => setInspectorOpen(true)}
              aria-label="Show inspector"
              title="Show inspector"
              className="shrink-0 w-6 hidden xl:flex items-start justify-center pt-3.5 text-[var(--i-text-faint)] hover:text-[var(--i-text)] transition-colors"
              style={{ background: "var(--i-panel)", borderLeft: "1px solid var(--i-border)" }}
            >
              ‹
            </button>
          )}
        </div>
      </div>

      <CommandMenu
        open={commandOpen}
        onClose={() => setCommandOpen(false)}
        scopes={data.scopes.map((s) => ({ scopeId: s.scopeId, name: s.name }))}
        onSelectScope={setSelectedScopeId}
      />

      <SplitPatchbay
        open={patchbayOpen}
        people={patchbayPeople}
        scopeNameById={scopeNameById}
        accentByScope={accentByScope}
        contextSwitchCostPct={switchCostPct}
        splits={splits}
        error={patchbayError}
        onSetSplit={onSetSplit}
        onRelabel={relabelPerson}
        onClose={() => {
          setPatchbayOpen(false);
          setPatchbayError(null);
        }}
      />
    </>
  );
}
