import { chromium } from "playwright";
import { mkdirSync } from "fs";
const OUT = process.env.OUT ?? "./b2shots";
mkdirSync(OUT, { recursive: true });
const V = process.argv[2] ?? "b";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const c = await b.newContext({ viewport: { width: 1400, height: 900 }, deviceScaleFactor: 2 });
const p = await c.newPage();
p.on("pageerror", (e) => console.log("PAGEERROR", e.message.slice(0,150)));
await p.goto(`http://localhost:4400/pb2.html?v=${V}`, { waitUntil: "networkidle" });
await p.waitForTimeout(2000);
await p.evaluate(() => window.__lab.fit()); await p.waitForTimeout(700);
await p.screenshot({ path: `${OUT}/b2${V}-1-rings.png` });
console.log("rings", JSON.stringify(await p.evaluate(() => ({ settle: Math.round(window.__lab.settleMs()), sep: window.__lab.groupSeparation() }))));
await p.evaluate(() => window.__lab.setMode("constellations"));
await p.waitForTimeout(5000);
await p.evaluate(() => window.__lab.fit()); await p.waitForTimeout(700);
await p.screenshot({ path: `${OUT}/b2${V}-2-constellations.png` });
console.log("cells", JSON.stringify(await p.evaluate(() => window.__lab.groupSeparation())));
await b.close();
